language: cpp
compiler:
  - gcc

before_install:
  - pip install cpp-coveralls
  - pip install pyopenssl

script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON
- cmake --build _build
- cmake --build _build --target install
- cmake --build _build --target test -- ARGS=--verbose
- cd _build
- cpack -G "DEB"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

after_success:
  - coveralls --exclude '_.*' --exclude 'third-party' --gcov-options '\-lp'

artifacts:
  - path: _build
    name: print-0.1.0.0-Linux.deb
